FROM node:20-alpine as builder
WORKDIR /ui
COPY ui/package.json ui/package-lock.json ./
RUN npm install
COPY ui ./
RUN npm run build

FROM node:20-alpine
WORKDIR /ui
COPY --from=builder /ui/dist ./dist
RUN npm install -g serve
CMD ["serve", "-s", "dist", "-l", "4173"]
